# C compiler
CC := cc

# Packages
override PACKAGES += xcb xcb-errors xcb-xkb xcb-randr xcb-icccm xcb-ewmh xkbcommon xkbcommon-x11

# Compiler flags
override CFLAGS += -std=c99 -D_XOPEN_SOURCE=700 -Iinclude \
           -Wall -Wextra -Wpedantic -Wno-format-zero-length \
           $(shell pkg-config --cflags $(PACKAGES))
# Add debug flags
DEBUG_FLAGS := -DDEBUG -g -fsanitize=address
override CFLAGS += $(DEBUG_FLAGS)

# Prefix of the build directory
BUILD_PREFIX := build

# Libraries
LDLIBS := $(shell pkg-config --libs $(PACKAGES))

# Sandbox parameters
SANDBOX_DISPLAY := :8
SANDBOX := Xephyr $(SANDBOX_DISPLAY)

# Find all source files (plus additional supplied by the command line)
override SOURCES += $(shell find src -name '*.c')
# Get all corresponding object paths
OBJECTS := $(patsubst %.c,$(BUILD_PREFIX)/%.o,$(SOURCES))
# Get all include files
INCLUDES := $(shell find include -name '*.h')

# Get dependencies
DEPENDENCIES := $(patsubst %.o,%.d,$(OBJECTS))

.PHONY: default
default: build

# Include dependencies (.d files) generated by gcc
-include $(DEPENDENCIES)
# Build each object from corresponding source file
$(BUILD_PREFIX)/%.o: %.c
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@ -MMD

# Build the main executable from all object files
$(BUILD_PREFIX)/smoke-wm: $(OBJECTS)
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(OBJECTS) -o $@ $(LDLIBS)

# Functions
.PHONY: analyze build sandbox clean

analyze:
	gcc -fanalyzer $(CFLAGS) $(SOURCES) $(LDLIBS)

build: $(BUILD_PREFIX)/smoke-wm

sandbox: build
	$(SANDBOX) &
	# wait for x server to start
	sleep 1
	DISPLAY=$(SANDBOX_DISPLAY) ./$(BUILD_PREFIX)/smoke-wm
	pkill Xephyr

gdb-sandbox: build
	$(SANDBOX) &
	# wait for x server to start
	sleep 1
	DISPLAY=$(SANDBOX_DISPLAY) gdb -ex run --args ./$(BUILD_PREFIX)/smoke-wm
	pkill Xephyr

# Only ever remove `build/` not `$(BUILD_PREFIX)` for safety
clean:
	rm -rf build/
